### ISSUE TITLE
Design Spike

### ISSUE THREAD

**Issue by fonzerelly** [Cinzya/domain-monitor#21]
Als PO möchte ich ein Gefühl dafür bekommen, wie die Applikation am Ende aussehen wird. Daher soll eine oder mehrere statische HTML-Seite angelegt werden, die die verschiedenen Eingabe- und Ausgabemasken der Applikation darstellt. 

### Voraussetzung
keine

### Akzeptanzkriterien:
* Es gibt eine statische Website für den Login
* Es gibt eine statische Website die zeigt wie der Nutzer eine neue Domain eingeben kann
* Es gibt eine statische Website für die Domainübersicht

### Storysize: M

**Comment by Cinzya** [comment]
Simple HTML & CSS Dateien erstellt und hinzugefügt.
