### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by fonzerelly** [Cinzya/domain-monitor#22]
Als PO möchte ich mir nach jedem Sprint einen Überblick über den Zustand der Applikation verschaffen können. Daher soll die Applikation über eine URL abrufbar sein.

Storysize: L

**Comment by fonzerelly** [comment]
Da sie ja eine Backendlösung anstreben könnten Sie überlegen Ihr Pojekt via Heroku zu veröffentlichen. Für die statischen Seiten aus [Design-Spike]https://github.com/Cinzya/domain-monitor/issues/21) würde aber auch das Deployment via github-pages genügen (D.h. wenn Sie einen branch namens "gh-pages" anlegen, dann wird der Inhalt dieses Branches über <username>.github.io/<repository-name> autmatisch veröffentlicht.

**Comment by Cinzya** [comment]
GIT Deployment mithilfe eines post-receive Hook zur Sub-Damain http://dm.cynthiaebert.de/ angelegt. 
Weitere Details zum Verfahren [hier](https://gist.github.com/noelboss/3fe13927025b89757f8fb12e9066f2fa) nachzulesen.
